

  services:
    db:
      image: postgres:15
      environment:
        POSTGRES_DB: ticketdb
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: adminpass
      volumes:
        - pgdata:/var/lib/postgresql/data

      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U admin"]
        interval: 10s
        retries: 5

    backend:
      build: ./backend
      depends_on:
        db:
          condition: service_healthy
      environment:
        DATABASE_URL: postgres://admin:adminpass@db:5432/ticketdb
        NODE_ENV: production
      ports:
        - "4003:4002"
        
      command: ["sh", "-c", "npm run migrate && npm run start"]

    frontend:
      build: ./frontend
      ports:
        - "3000:80"
      depends_on:
        backend:
          condition: service_started

  volumes:
    pgdata:

# version: '3.8'

# services:
#   db:
#     image: postgres:15
#     environment:
#       POSTGRES_DB: ticketdb
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: adminpass
#     volumes:
#       - pgdata:/var/lib/postgresql/data

#   backend:
#     build:
#       context: ./Backend-migration
#     ports:
#       - "4002:4002"
#     depends_on:
#       - db
#     environment:
#       - DB_HOST=db
#       - DB_PORT=5432
#       - DB_USER=admin
#       - DB_PASSWORD=adminpass
#       - DB_NAME=ticketdb
#       - JWT_SECRET=super_secret_key_123
#       - JWT_EXPIRES_IN=1d

# volumes:
#   pgdata:
